import { defineConfig } from 'vitest/config'
import vue from '@vitejs/plugin-vue'
import { resolve } from 'node:path'

// Resolve paths from .nuxt/tsconfig.json (generated by `nuxt prepare`)
// These packages are not direct deps of apps/web but are installed by Nuxt.
const nuxtModules = resolve(__dirname, '../../node_modules/.pnpm')
const vuePath = resolve(nuxtModules, 'vue@3.5.32_typescript@5.9.3/node_modules/vue')

export default defineConfig({
  plugins: [vue()],
  test: {
    environment: 'happy-dom',
    setupFiles: ['./tests/setup.ts'],
    globals: true,
  },
  resolve: {
    alias: {
      'vue': vuePath,
      '@ai-real-estate/shared-types': resolve(__dirname, '../../packages/shared-types/src/index.ts'),
      '@ai-real-estate/shared-utils': resolve(__dirname, '../../packages/shared-utils/src/index.ts'),
      '@ai-real-estate/ui': resolve(__dirname, '../../packages/ui/src/index.ts'),
    },
  },
})
