[phases.setup]
nixPkgs = [
  "php83",
  "php83Extensions.pdo",
  "php83Extensions.pdo_sqlite",
  "php83Extensions.mbstring",
  "php83Extensions.openssl",
  "php83Extensions.curl",
  "php83Extensions.tokenizer",
  "php83Extensions.xml",
  "php83Extensions.ctype",
  "php83Extensions.fileinfo"
]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader --no-interaction"]

[start]
cmd = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"
